### ISSUE TITLE
Error in source(validate.R)

### ISSUE THREAD

**Issue by danshu** [lilit-nersisyan/computel#1] opened 2016-10-17 15:47 UTC
Hi,

Here is the error message:
"Error in source(validate.R) : 
validate.options.R:165:74: unexpected input
164:         if (OS.name == "windows"){
165:     cat("compressed fastq files may not be given as input on Windows OS")\
                                                                              ^
Execution halted"

Best,
Quan

**Comment by lilit-nersisyan** [comment] 2016-10-18 10:14
Hi Quan, 

Could you, please, send the configuration file you use and name the OS ? 

Thanks, 
Lilit

**Comment by danshu** [comment] 2016-10-18 10:24
Hi Lilit,

Please find the attached configure file. The OS is  Ubuntu 15.10.

Thanks,
Quan
[config.txt](https://github.com/lilit-nersisyan/computel/files/535955/config.txt)

**Comment by lilit-nersisyan** [comment] 2016-10-18 10:35
Dear Quan, 

Can you try upgrading the Computel version? These lines are in the previous version of "validate.R". Please, try the last version and let me know if this resolves the issue. 

Cheers, 
Lilit

**Comment by danshu** [comment] 2016-10-18 10:49
Hi Lilit,

I'm using version 0.2. That configuration file was modified from the configuration from the "example" directory.  I also tries this configuration file, 
[computel.R.txt](https://github.com/lilit-nersisyan/computel/files/535998/computel.R.txt)
but with the same error.

Best,
Quan

**Comment by lilit-nersisyan** [comment] 2016-10-18 11:01
Dear Quan, 

Please, update the scripts (not the config file) from the src folder to their current versions. The problem is in the scripts, and this bug should be fixed already. 

Cheers,
Lilit

**Comment by danshu** [comment] 2016-10-18 12:32
Hi Lilit,

Thanks for you help. I'm running computel now.

Best,
Quan

**Closed as completed** 2016-10-18 15:18 UTC
